const TURBO_FONT_CSS_DEFAULT_FOLDER       = 'src/css';
const TURBO_FONT_CSS_DEFAULT_FILENAME     = 'font-icons.css';
const TURBO_FONT_CSS_REPLACER_FOLDER      = '../fonts/';
const GENERATED_FONT_CSS_DEFAULT_FOLDER   = 'dist';
const GENERATED_FONT_CSS_DEFAULT_FILENAME = 'font-icons.css';
const EXPORTED_CONFIG_DEFAULT_FILENAME    = 'icons.config.js';

module.exports = {
    TURBO_FONT_CSS_DEFAULT_FOLDER,
    TURBO_FONT_CSS_DEFAULT_FILENAME,
    GENERATED_FONT_CSS_DEFAULT_FOLDER,
    GENERATED_FONT_CSS_DEFAULT_FILENAME,
    EXPORTED_CONFIG_DEFAULT_FILENAME,
    TURBO_FONT_CSS_REPLACER_FOLDER
}
