export const REQUEST_LIST_USERS_PRESENCE    = "PRESENCE-AND-COLLAB/REQUEST_LIST_USERS_PRESENCE";
export const SET_LIST_USERS_PRESENCE        = "PRESENCE-AND-COLLAB/SET_LIST_USERS_PRESENCE";
export const ADD_USER_TO_PRESENCE           = "PRESENCE-AND-COLLAB/ADD_USER_TO_PRESENCE";
export const REMOVE_USER_FROM_PRESENCE      = "PRESENCE-AND-COLLAB/REMOVE_USER_FROM_PRESENCE";
export const CHANGE_USER_STATUS_IN_PRESENCE = "PRESENCE-AND-COLLAB/CHANGE_USER_STATUS_IN_PRESENCE";
